### PR TITLE
Corrected mistaken claim of being open source

### PR DESCRIPTION
**Pull request by justinclift**
CC-NC licenses aren't open source, so need more accurate wording.
Hope this is suitable. :)

### CODE REVIEW

**Comment by garrett** [comment]
Firstly: Thanks for the project and for releasing the code. Also, thanks for the clarification!

However, it's important to point out that Creative Commons licenses do not really work well for code, as they are intended for media: 
https://wiki.creativecommons.org/Frequently_Asked_Questions#Can_I_apply_a_Creative_Commons_license_to_software.3F

It would be ideal to relicense the software using an OSI-approved license. There's a good list of popular open source licenses at http://opensource.org/licenses/ (MIT, GPL, BSD, Apache, and MPL are the most popular.)

**Comment by quasado** [comment]
hi,

Thanks for writing us. Yes, the license is causing somewhat troubles :-|

See, there seems to be no real license fitting our intentional goals:

We want everyone to learn from our code and also create derivates from it.
But we do _not_ want anyone to use the code in commercial projects.

this is simply because we’ve spend so much money in this project we do not want other companies to simply take it for granted and make money with our work if you understand what I mean.

Alex

**Comment by justinclift** [comment]
No worries Alex.  That's a common worry for people doing development in Open Source Communities. :smile:  If I had the spare time, I'd help walk you through potential options.  I don't atm though. :frowning: _sigh_

Have you reached out to the Open Source Institute for assistance?

Also, are you wanting to accept Pull Requests from people (not in your company) with the main Gravit repo?

**Comment by quasado** [comment]
hi,

Nope didn’t reach out yet though that’s a good hint and I’ll go for that.

Yeah sure, we’re absolutely accepting pull requests to the main repo from anyone! :)

Alex

**Comment by justinclift** [comment]
Cool.  :smile:

Something I'm personally not sure of, and you want to check with the OSI people, is what happens when you accept external contributions to a CC-NC licensed project.  From memory you're wanting to build a central hub type service to interact with this software, and that **may** (unsure) be a problem.

**Pull request merged**
